# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node runtime as a parent image
FROM node:20-slim AS build

# Install bun
RUN curl -fsSL https://bun.sh/install | bash

# Set the working directory in the container
WORKDIR /app

# Copy package.json and bun.lockb for dependency installation
COPY package.json bun.lockb ./

# Install project dependencies
RUN /root/.bun/bin/bun install

# Copy the rest of the application code
COPY . .

# Build the application
RUN /root/.bun/bin/bun run build

# Use a smaller Node image for running the application
FROM node:20-slim AS production

# Set the working directory in the container
WORKDIR /app

# Copy the built application from the build stage
COPY --from=build /app/dist /app/dist

# Set the entrypoint
ENTRYPOINT ["node", "/app/dist/main.js"]
